/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatModal: typeof import('./components/ChatModal.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    Footer: typeof import('./components/commen/footer/footer.vue')['default']
    Header: typeof import('./components/commen/header/header.vue')['default']
    HeaderSelect: typeof import('./components/commen/header/header-select.vue')['default']
    ImageUpload: typeof import('./components/ImageUpload.vue')['default']
    Layout: typeof import('./components/commen/layout.vue')['default']
    ReplyNode: typeof import('./components/ReplyNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentCenterCourseList: typeof import('./components/studentCenter/StudentCenterCourseList.vue')['default']
    StudentDashboard: typeof import('./components/studentCenter/StudentDashboard.vue')['default']
    TeacherHeader: typeof import('./components/commen/header/TeacherHeader.vue')['default']
    VideoUpload: typeof import('./components/VideoUpload.vue')['default']
  }
}
