/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    Footer: typeof import('./components/commen/footer/footer.vue')['default']
    Header: typeof import('./components/commen/header/header.vue')['default']
    HeaderSelect: typeof import('./components/commen/header/header-select.vue')['default']
    Layout: typeof import('./components/commen/layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeacherHeader: typeof import('./components/commen/header/TeacherHeader.vue')['default']
  }
}
